/**
 * @file player_profile.cpp
 * @brief Player profile implementation: levelling, unlocks and persistence.
 */

#include "core/player_profile.h"

#include <algorithm>
#include <cctype>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <sstream>

namespace hexapp {

    namespace {
        /** @brief Experience key in the file. */
        constexpr const char* KEY_XP = "xp";

        /** @brief Length past which a line means a corrupt file, not data. */
        constexpr std::size_t MAX_PROFILE_LINE = 512;

        /** @brief Strips leading and trailing whitespace. */
        std::string trim(const std::string& text) {
            const auto first = text.find_first_not_of(" \t\r\n");
            if (first == std::string::npos) return {};

            const auto last = text.find_last_not_of(" \t\r\n");
            return text.substr(first, last - first + 1);
        }

        /** @brief Lowercases text for case-insensitive key matching. */
        std::string lowered(std::string text) {
            std::ranges::transform(text, text.begin(), [](const unsigned char c) {
                return static_cast<char>(std::tolower(c));
            });
            return text;
        }
    }

    int levelFor(const int xp) {
        // Levels start at 1: a player who has never played is level one, not zero.
        // A negative value can only come from a tampered file and counts as none.
        if (xp <= 0) return 1;
        return 1 + std::min(xp, MAX_XP) / XP_PER_LEVEL;
    }

    int xpIntoLevel(const int xp) {
        if (xp <= 0) return 0;
        return std::min(xp, MAX_XP) % XP_PER_LEVEL;
    }

    hexui::StringKey titleKeyFor(const int level) {
        switch (level) {
            case 1:  return hexui::StringKey::RANK_ROOKIE;
            case 2:  return hexui::StringKey::RANK_HACKER;
            case 3:  return hexui::StringKey::RANK_MASTERMIND;
            default: break;
        }
        // The ladder stops here: advertising ranks nobody will reach is an empty
        // promise.
        return hexui::StringKey::RANK_LEGEND;
    }

    int requiredLevelFor(const BoardPalette palette) {
        switch (palette) {
            case BoardPalette::TOXIC:    return 2;
            case BoardPalette::PRESTIGE: return 3;
            default:                     break;
        }
        return 1;   // the classic scheme is never locked
    }

    bool isPaletteUnlocked(const BoardPalette palette, const int xp) {
        return levelFor(xp) >= requiredLevelFor(palette);
    }

    BoardPalette usablePalette(const BoardPalette chosen, const int xp) {
        return isPaletteUnlocked(chosen, xp) ? chosen : BoardPalette::CLASSIC;
    }

    Profile withXpGain(const Profile& profile, const int gain) {
        Profile next = profile;

        // Gains are clamped non-negative and the total saturates at MAX_XP. The
        // sum runs in long long because two individually valid values can still
        // overflow an int once added.
        const long long raw = static_cast<long long>(std::max(0, profile.xp))
                            + std::max(0, gain);

        next.xp = static_cast<int>(std::min<long long>(raw, MAX_XP));
        return next;
    }

    std::string serializeProfile(const Profile& profile) {
        std::ostringstream out;
        out << "# HEX - player profile\n"
            << "# Generated by the game; safe to edit by hand.\n"
            << KEY_XP << '=' << profile.xp << '\n';
        return out.str();
    }

    Profile parseProfile(const std::string& text) {
        Profile profile;   // the default is the baseline; the file only amends it

        std::istringstream in(text);
        std::string line;

        while (std::getline(in, line)) {
            if (line.size() > MAX_PROFILE_LINE) continue;
            if (!line.empty() && line.back() == '\r') line.pop_back();

            const std::string stripped = trim(line);
            if (stripped.empty() || stripped.front() == '#' || stripped.front() == ';') continue;
            if (stripped.front() == '[') continue;   // ini sections are ignored

            const std::size_t separator = stripped.find('=');
            if (separator == std::string::npos) continue;

            const std::string key = lowered(trim(stripped.substr(0, separator)));
            const std::string value = trim(stripped.substr(separator + 1));
            if (key.empty() || value.empty()) continue;

            if (key != KEY_XP) continue;   // future keys: ignored, not rejected

            // Digits only: a signed value is not experience, and accepting one
            // would let a text editor take levels away.
            if (!std::ranges::all_of(value, [](const unsigned char c) {
                    return c >= '0' && c <= '9';
                })) {
                continue;
            }

            // An oversized number saturates at the ceiling rather than being
            // dropped: dropping it would reset the profile to zero, punishing a file
            // that claims too much progression with the loss of all of it. Excess
            // digits are caught by length before conversion, which is where a parse
            // would overflow instead of saturating.
            constexpr std::size_t MAX_DIGITS = 9;   // fits comfortably in an int
            if (value.size() > MAX_DIGITS) {
                profile.xp = MAX_XP;
                continue;
            }

            profile.xp = static_cast<int>(std::min(std::strtol(value.c_str(), nullptr, 10),
                                                   static_cast<long>(MAX_XP)));
        }

        return profile;
    }

    Profile loadProfile(const std::string& path) {
        std::ifstream in(path, std::ios::binary);
        if (!in) return {};   // first run: a fresh profile is exactly right

        std::ostringstream buffer;
        buffer << in.rdbuf();
        return parseProfile(buffer.str());
    }

    bool saveProfile(const Profile& profile, const std::string& path) {
        // The profile lives in saves/, which may not exist yet on a first run;
        // create it, as saving a game does.
        if (const std::filesystem::path parent = std::filesystem::path(path).parent_path();
            !parent.empty()) {
            std::error_code ec;
            std::filesystem::create_directories(parent, ec);
            if (ec) return false;
        }

        std::ofstream out(path, std::ios::binary | std::ios::trunc);
        if (!out) return false;

        out << serializeProfile(profile);
        return static_cast<bool>(out);
    }
}
